#Spring Boot 配置文件:
#端口
server:
  port: 8080

spring:
  #数据源
  datasource:
    #数据库访问配置
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/movie?autoReconnect=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/movie?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    #连接池配置
    # 初始化时建立物理连接的个数
    initialSize: 10
    # 最小连接池数量
    minIdle: 10
    # 最大连接池数量
    maxActive: 20
    # 连接时最大等待时间,单位毫秒
    maxWait: 60000
    # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sql,要求是一个查询语句
    validationQuery: SELECT 1 FROM DUAL
    # 申请连接时执行 validationQuery 检测连接是否有效,做了这个配置会降低性能
    testOnBorrow: false
    # 归还连接时执行 validationQuery 检测连接是否有效,做了这个配置会降低性能
    testOnReturn: false
    # 建议配置为true,不影响性能,并且保证安全性;申请连接的时候检测,
    # 如果空闲时间大于 timeBetweenEvictionRunsMillis,执行 validationQuery 检测连接是否有效
    testWhileIdle: true
    # 是否缓存preparedStatement,也就是 PSCache
    poolPreparedStatements: true
    # 指定每个连接上 PSCache 的大小
    maxOpenPreparedStatements: 20
    # 配置监控统计拦截的filters,属性类型是字符串,通过别名的方式配置扩展插件,
    # 常用的插件有:监控统计用的stat;日志用的log4j;防御sql注入的wall
    filters: stat,wall,log4j
    # 通过 connectProperties 属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

#mybatis
  mybatis-plus:
    #把xml文件放在com.XX.mapper.*中可能会出现找到的问题,这里把他放在resource下的mapper中
    mapper-locations: classpath:/mapper/*Mapper.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.gy.demo.entity
    typeEnumsPackage: com.baomidou.springboot.entity.enums
    global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 2
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.gy.demo.xxx
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      #自定义填充策略接口实现
      #meta-object-handler: com.gy.demo.xxx
      #自定义SQL注入器
      #sql-injector: com.gy.demo.xxx
      configuration:
        #驼峰转换
        map-underscore-to-camel-case: true
        #全局缓存处理
        cache-enabled: false

#logging
